FROM python:3.7.3-stretch

## Complete Step 1:
WORKDIR /app

## Complete Step 2:
COPY app.py ./app/

## Complete Step 3:
RUN pip3 install -r requirements.txt
hadolint ignore=DL3013

## Complete Step 4:
# Expose port 80

## Complete Step 5:
# Run app.py at container launch
